export const types = {
  FETCH_COUNTERS_REQUEST: "FETCH_COUNTERS_REQUEST",
  FETCH_COUNTERS_SUCCESS: "FETCH_COUNTERS_SUCCESS",
  FETCH_COUNTERS_FAILURE: "FETCH_COUNTERS_FAILURE",
  ADD_COUNTER: "ADD_COUNTER",
  INC_COUNTER: "INC_COUNTER",
  DEC_COUNTER: "DEC_COUNTER",
  DELETE_COUNTER: "DELETE_COUNTER",
  SET_SHOW_ADD_COUNTER_FORM: "SET_SHOW_ADD_COUNTER_FORM",
  SET_SORT_BY: "SET_SORT_BY",
};
